---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: storage
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfs-subdir
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    nfs:
      server: "172.16.10.15"
      path: "/volume1/cloudnative"
      mountOptions:
        - noatime
        - nodiratime
        - nfsvers=4
    storageClass:
      defaultClass: false
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
      onDelete: retain
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nfs-subdir-external-provisioner
              topologyKey: kubernetes.io/hostname
