---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minio
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2023-12-14T18-51-57Z
    env:
      MINIO_UPDATE: "off"
      MINIO_PROMETHEUS_AUTH_TYPE: public
      #MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      MINIO_PROMETHEUS_JOB_ID: minio
      #MINIO_BROWSER_REDIRECT_URL: "https://minio.monosense.io"
      MINIO_SERVER_URL: "https://ecs.monosense.io"
      MINIO_API_CORS_ALLOW_ORIGIN: https://minio.monosense.io,https://ecs.monosense.io
    envFrom:
      - secretRef:
          name: minio-secret
    args:
      - server
      - /data
      - --console-address
      - :9001
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: &console-port 9001
          api:
            enabled: true
            port: &api-port 9000
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: api
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /minio/health/live
            port: *api-port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &console-host minio.monosense.io
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *console-port
        tls:
          - secretName: minio.monosense.io
            hosts:
              - *console-host
      s3:
        enabled: true
        ingressClassName: internal-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
          nginx.ingress.kubernetes.io/proxy-body-size: 10240m
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            chunked_transfer_encoding off;
        hosts:
          - host: &api-host ecs.monosense.io
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *api-port
        tls:
          - secretName: minio-s3-tls
            hosts:
              - *api-host

    persistence:
      data:
        existingClaim: minio-data-nfs
        globalMounts:
          - path: /data
