---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-reloader
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/reloader/app
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: infra-cluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: reloader
  prune: true
  wait: false
  interval: 10m
