---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s.yaml
  - cilium.yaml
  - democratic-csi.yaml
  - external-secrets.yaml
  - gitlab.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - k8tz.yaml
  - kubernetes-sigs-external-dns.yaml
  - kubernetes-sigs-nfd.yaml
  - postfinance.yaml
  - prometheus-community.yaml
  - stakater.yaml
  - weave-gitops.yaml
