---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: emqx
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: infra-synology-csi
      namespace: kube-system
  values:
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
    service:
      type: LoadBalancer
      annotations:
        cert-manager.io/cluster-issuer: buypass-staging
        external-dns.alpha.kubernetes.io/hostname: mqtt.monosense.io
        io.cilium/lb-ipam-ips: 10.11.11.2
    ingress:
      dashboard:
        enabled: true
        ingressClassName: internal-nginx
        path: /
        pathType: Prefix
        hosts:
          - &host mqtt.monosense.io
        tls:
          - hosts:
              - *host
    metrics:
      enabled: true
    persistence:
      enabled: true
      storageClassName: synology-iscsi-retain
      size: 1Gi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values: ["emqx"]
  valuesFrom:
    - targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: admin_password
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__USERNAME
      kind: Secret
      name: emqx-secret
      valuesKey: user_1_username
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: user_1_password
