---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname infra-intel-device-plugins-operator
  namespace: flux-system
spec:
  targetNamespace: system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: "./kubernetes/apps/system/intel-device-plugins/operator"
  sourceRef:
    kind: GitRepository
    name: infra-cluster
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: infra-cert-manager
    - name: infra-node-feature-discovery
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname infra-intel-device-plugins-gpu
  namespace: flux-system
spec:
  targetNamespace: system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: "./kubernetes/apps/system/intel-device-plugins/gpu"
  sourceRef:
    kind: GitRepository
    name: infra-cluster
  interval: 30m
  prune: true
  wait: true
  dependsOn:
    - name: infra-intel-device-plugins-operator
