---
# https://docs.cilium.io/en/latest/network/l2-announcements
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  loadBalancerIPs: true
  interfaces:
    - ^eno[0-9]+
    - ^eth[0-9]+
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-layer2: "true"
