---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-meshcentral
  namespace: flux-system
spec:
  path: ./kubernetes/apps/network/meshcentral/app
  targetNamespace: network
  sourceRef:
    kind: GitRepository
    name: infra-cluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: meshcentral
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: infra-synology-csi
    - name: infra-nginx-internal
