# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:tv5qS5FYSq/3ZM3q,iv:hH3JHCKqKE7TiR4bHPYTNwY4MA+h/hgBxRQhJLDinNY=,tag:3jXOColaKQH4+j4W9jHjyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3hsfptdfsfwvkf504etjkrtmajny9csrfh5s24uqh6fchmg5dgqg087ek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bndVZ0QyeXlpZWZGTUlW
            QktKQXY2YU1OVzJiYkpzRWpQc1BJLytWSFNjCmcwM1FCZDNFVzZHK0JBbkQvY0Nq
            ZC9qUTNtcVBzMDhYN2ppRTRYbkxTM2cKLS0tIFVOamtsa0puRno1cDZ1YVdoSXRU
            Nk03bVIxbTh3YkxsVWpzQXg0MC9remsKHPyGjAQtGkWKEtXqFzSYcQtK49vxDBmv
            mdRnIJNHTUFbtMe2mGWMYwkB2MGeBXN/fRGnfbxTr8c2y7fcBWYe1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-09T12:15:58Z"
    mac: ENC[AES256_GCM,data:yR0SviKHbu3Oeel+kjQnm0jcKswULEzP9YTrKQhTfKBQb8N2fz74Ncu7TF4x6vDE3+EGTcil9BBJmpZ5VTqe7C0zZdSuS0lNBPb+/fQl+VFlqr4FGbDrkTUmS0bd8+mYOBQY8eBv8YYmUn5rS+M5C30Mf8ySNQY5YMn8vTTnVNg=,iv:4hN+4w10AyQTDqPi/5iNErCUpjAB3NE2ppqZtxxxh2w=,tag:imvQnij1Yw9oqbSj83lfYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
