---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-nfs-subdir
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/storage/nfs-subdir/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-cluster
  wait: true
  postBuild:
    substituteFrom: []
