---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name client-info-secret
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-info.yml: |
          clients:
            - host: {{ .synology_host }}
              port: {{ .synology_port }}
              https: false
              username: {{ .synology_username }}
              password: {{ .synology_password }}

  dataFrom:
    - extract:
        key: democratic-csi
